version: '3.4'

services:
  acmecorp:
    image: acmecorp:dev
    container_name: ACMECorp
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ACMECorp"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_acmecorp$
    volumes:
      - D:\ACMECorp\ACMECorp\ACMECorp:/app
      - D:\ACMECorp\ACMECorp:/src
      - C:\Users\s_balaji\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_acmecorp$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_acmecorp$ \"/app/bin/Debug/net5.0/ACMECorp.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true