version: '3.4'

services:
  acmecorp:
    image: ${DOCKER_REGISTRY-}acmecorp
    build:
      context: .
      dockerfile: ACMECorp/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - ConnectionStrings__Default=postgres://root:password@localhost:5432/ACMECorp

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ACMECorp